apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager-ns.yaml
- lets-encrypt-issuer.yaml

helmCharts:
- name: cert-manager
  version: 1.6.1
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
  namespace: cert-manager
  releaseName: cert-manager
