apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rollouts-demo
spec:
  rules:
  - host: rollouts-demo-desired.apps.jessesuen.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rollouts-demo-desired
          servicePort: 80
  - host: rollouts-demo-stable.apps.jessesuen.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rollouts-demo-stable
          servicePort: 80
  - host: rollouts-demo.apps.jessesuen.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rollouts-demo
          servicePort: 80
