apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-cd.yaml
- appset.yaml
- argocd-server-ing.yaml

patchesStrategicMerge:
- argocd-cm.yaml
- argocd-rbac-cm.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-server
  path: argocd-server-deploy-insecure.yaml
